version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
#    environment:
#      - REDIS_PASSWORD=yourStrongPassword123!  # Set the password for Redis
#    command: redis-server --requirepass ${REDIS_PASSWORD}  # Start Redis with password requirement

volumes:
  redis_data: