version: '3.8'

services:
#  redis:
#    image: redis:latest
#    container_name: my_redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    command: [ "redis-server", "--requirepass", "password" ]
#    networks:
#      - msc

  phpui:
    build: .
    container_name: php-ui
    ports:
      - "80:80"
    environment:
      - POSTGRESHOST=postgres
      - POSTGRESPORT=5432
      - POSTGRESDBNAME=mscstudents
      - POSTGRESUSER=student
      - POSTGRESPASSWORD=password
      - USER_SERVICE_URI=http://localhost:9091/api/v1
      - ITEM_SERVICE_URI=http://localhost:9092/api/v1
      - REDIS_URL=tcp://sever3d.synology.me:6379?auth=password
      - ACADEMICHAIN_ENV=dev
    networks:
      - msc

  users-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
    command:
      - "--url=jdbc:postgresql://postgres:5432/mscstudents"
      - "--username=student"
      - "--password=password"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=uilogs"
      - "update"
    networks:
      - msc

networks:
  msc:
    name: msc-localdev_msc
    driver: bridge
    external: true

volumes:
  redis_data: