version: '3.8'

services:
  academi-ui:
    image: sever3d/academichain-ui
    pull_policy: always
    ports:
      - "80:80"
    environment:
      - ACADEMICHAIN_ENV=${ACADEMICHAIN_ENV}
      - POSTGRESHOST=${POSTGRESHOST}
      - POSTGRESPORT=${POSTGRESPORT}
      - POSTGRESDBNAME=${POSTGRESDBNAME}
      - POSTGRESUSER=${POSTGRESUSER}
      - POSTGRESPASSWORD=${POSTGRESPASSWORD}
      - CORE_SERVICE_URI=${CORE_SERVICE_URI}
      - USER_SERVICE_URI=${USER_SERVICE_URI}
      - ITEM_SERVICE_URI=${ITEM_SERVICE_URI}
      - NLP_SERVICE_URI=${NLP_SERVICE_URI}
      - NLP_SERVICE_TOKEN=${NLP_SERVICE_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - KEYCLOAK_AUTH_URL=${KEYCLOAK_AUTH_URL}
    depends_on:
      - ui-database-migrations
    networks:
      - msc

  ui-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
    command:
      - "--url=jdbc:postgresql://postgres:5432/mscstudents"
      - "--username=student"
      - "--password=password"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=uilogs"
      - "update"
    networks:
      - msc

networks:
  msc:
    name: msc-localdev_msc
    driver: bridge
    external: true
