version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  users-database-migrations:
    image: "liquibase/liquibase:4.15.0"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql
    command:
      - "--url=jdbc:postgresql://postgres:5432/mscstudents"
      - "--username=student"
      - "--password=password"
      - "--changeLogFile=changelog/db.changelog-main.yml"
      - "--liquibaseSchemaName=uilogs"
      - "update"
    networks:
      - msc

networks:
  msc:
    name: msc-localdev_msc
    driver: bridge
    external: true


volumes:
  redis_data: