<?php
include_once 'fns_curl.php';
include_once 'fns_user.php';
include_once 'fns_crypto.php';

$VIEW = isset($VIEW) ? $VIEW : 'index';

switch ($VIEW) {

	case 'index':
            // Attach js files to the footer
			$jsfiles = [];

            if(isUserLoggedIn()) {
                // Get logged in user
                //$USER = $_SESSION['user'];

                // Log user login by presence of session variable 'justLoggedIn'
                // Each login is saved as db log
                if (isset($_SESSION['justLoggedIn'])) {
                    insertDbLogData('INFO', 'IndexController::index', 'user login', 'new user login');
                    unset($_SESSION['justLoggedIn']); // unset variable so new log are not created
                }

                // Use curl to get data from API
                $sessionUserName = $_SESSION['user']['username'];

                // Check if user exists in DB
                // Keycloak user is not equal DB user.
                // If DB user not exist then register him using Session data
                $userExists = user_get('username', $sessionUserName);
                if (!$userExists) {
                    $insertResult = user_insert_from_session(); // Create user in DB
                    $insertedUser = json_decode($insertResult['body'], true);
                    $_SESSION['user']['visibleUsername'] = $insertedUser['visibleUsername']; // auto-generated by API username
                    $_SESSION['user']['id'] = $insertedUser['id'];
                    // Get user again with all data from DB now
                    $userExists = user_get('username', $sessionUserName);
                } else {
                    $_SESSION['user']['visibleUsername'] = $userExists['visibleUsername'];
                    $_SESSION['user']['id'] = $userExists['id'];
                }

                $MAIN_USER = new User();
                $MAIN_USER->createUserFromSession();
                $MAIN_USER->setTokens($userExists['tokens']);
                $MAIN_USER->setCollege($userExists['college']);
                $MAIN_USER->setCollegeId($userExists['collegeid']);

                // Add User Session values
                $_SESSION['user']['collegeId'] = $MAIN_USER->getCollegeId();

                // Get user questions and questions count
                $userQuestions = user_get_questions($MAIN_USER->getId());
                if($userQuestions) {
                    $_SESSION['user']['questions-size'] = count($userQuestions);
                }
                $MAIN_USER->setQuestions($userQuestions);

                // TODO: Get user answers count
                $userAnswers = user_get_answers($MAIN_USER->getId());
                if($userAnswers) {
                    $_SESSION['user']['answers-size'] = count($userAnswers);
                }
                $MAIN_USER->setAnswers($userAnswers);

            }
	break;

	case 'logout':
		session_unset();
		session_destroy();
		header("Location: index.php");
	break;
	
	default:
		// code...
	break;
}

