<?php
include_once 'fns_curl.php';
include_once 'fns_user.php';
include_once 'fns_crypto.php';
include_once 'fns_module_college.php';

$VIEW = isset($VIEW) ? $VIEW : 'index';

switch ($VIEW) {

	case 'index':
            // Attach js files to the footer
			$jsfiles = [];

            if(isUserLoggedIn()) {
                // Get logged in user
                //$USER = $_SESSION['user'];

                // Log user login by presence of session variable 'justLoggedIn'
                // Each login is saved as db log
                if (isset($_SESSION['justLoggedIn'])) {
                    insertDbLogData('INFO', 'IndexController::index', 'user login', 'new user login');
                    unset($_SESSION['justLoggedIn']); // unset variable so new log are not created
                }

                // Use curl to get data from API
                $sessionUserName = $_SESSION['user']['username'];

                // Check if user exists in DB
                // Keycloak user is not equal DB user.
                // If DB user not exist then register him using Session data
                $userExists = user_get('username', $sessionUserName);
                if (!$userExists) {
                    $insertResult = user_insert_from_session(); // Create user in DB
                    $insertedUser = json_decode($insertResult['body'], true);
                    $_SESSION['user']['visibleUsername'] = $insertedUser['visibleUsername']; // auto-generated by API username
                    $_SESSION['user']['id'] = $insertedUser['id'];
                    // Get user again with all data from DB now
                    $userExists = user_get('username', $sessionUserName);
                } else {
                    $_SESSION['user']['visibleUsername'] = $userExists['visibleUsername'];
                    $_SESSION['user']['id'] = $userExists['id'];
                }

                $MAIN_USER = new User();
                $MAIN_USER->createUserFromSession();
                $MAIN_USER->tokens = $userExists['tokens'];
                $MAIN_USER->college  = $userExists['college'];
                $MAIN_USER->collegeId = $userExists['collegeid'];

                // Add User Session values
                $_SESSION['user']['collegeId'] = $MAIN_USER->colegeId;

                // Get user questions and questions count
                $userQuestions = user_get_questions($MAIN_USER->id);
                if(count($userQuestions)>0) {
                    $_SESSION['user']['questions-size'] = count($userQuestions);
                    $_SESSION['user']['questions'] = $userQuestions;
                }
                $MAIN_USER->questions = $userQuestions;

                // TODO: Get user answers count
                $userAnswers = user_get_answers($MAIN_USER->id);
                if($userAnswers) {
                    $_SESSION['user']['answers-size'] = count($userAnswers);
                    $_SESSION['user']['answers'] = $userAnswers;
                }
                $MAIN_USER->answers  = $userAnswers;


                if(!isset($_SESSION['user']['college_modules'])){
                    // Set user college modules as Session var to limit APi calls
                    $_SESSION['user']['college_modules'] = modules_get_by_college_id($MAIN_USER->collegeId);
                }


            }
	break;

	case 'logout':
		session_unset();
		session_destroy();
		header("Location: index.php");
	break;
	
	default:
		// code...
	break;
}

