<?php
include_once 'fns_curl.php';
include_once 'fns_user.php';
include_once 'fns_crypto.php';
include_once 'fns_module_college.php';

$VIEW = isset($VIEW) ? $VIEW : 'index';

switch ($VIEW) {

	case 'index':
            // Attach js files to the footer
			$jsfiles = [];

            if(isUserLoggedIn()) {
                // Get logged in user
                //$USER = $_SESSION['user'];

                // Log user login by presence of session variable 'justLoggedIn'
                // Each login is saved as db log
                if (isset($_SESSION['justLoggedIn'])) {
                    insertDbLogData('INFO', 'IndexController::index', 'user login', 'new user login');
                    unset($_SESSION['justLoggedIn']); // unset variable so new log are not created
                }

                // Use curl to get data from API
                $sessionUserName = $_SESSION['user']['username'];

                // Check if user exists in DB
                // Keycloak user is not equal DB user.
                // If DB user not exist then register him using Session data
                $foundUser = $USER_SERVICE->getUser('username', $sessionUserName);
                if (!$foundUser) {
                    $insertResult = $USER_SERVICE->user_insert_from_session(); // Create user in DB
                    $insertedUser = json_decode($insertResult['body'], true);
                    $_SESSION['user']['visibleUsername'] = $insertedUser['visibleUsername']; // auto-generated by API username
                    $_SESSION['user']['id'] = $insertedUser['id'];
                    // Get user again with all data from DB now
                    $foundUser = $USER_SERVICE->getUser('username', $sessionUserName);
                } else {
                    // Insert found user data into session to have quick access
                    $_SESSION['user']['visibleUsername'] = $foundUser['visibleUsername'];
                    $_SESSION['user']['id'] = $foundUser['id'];
                    $_SESSION['user']['tokens'] = $foundUser['tokens'];
                    $_SESSION['user']['imageid'] = $foundUser['imageid'];
                }

                $MAIN_USER = new User();
                $MAIN_USER->createUserFromSession();
                $MAIN_USER->tokens = $foundUser['tokens'];
                $MAIN_USER->college  = $foundUser['college'];
                $MAIN_USER->collegeId = $foundUser['collegeid'];
                $MAIN_USER->questions = $_SESSION['user']['questions'];
                $MAIN_USER->answers  = $_SESSION['user']['answers'];
                $MAIN_USER->imageid  = $_SESSION['user']['imageid'];

                $_SESSION['user']['collegeId'] = $foundUser['collegeid'];

            }
	break;

	case 'logout':
		session_unset();
		session_destroy();
		header("Location: index.php");
	break;
	
	default:
		// code...
	break;
}

